### ISSUE TITLE
abundance_year_compare does not save

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#23] opened 2023-10-30 12:35 UTC
when using this for 2021:2022, it displays a correct image but throws an error instead of saving the graph
![image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/875f630b-aeea-47d3-a699-549c42297811)

**Comment by ScientiaFelis** [comment] 2023-10-30 16:56
Cannot reproduce error!?

**Comment by larspett** [comment] 2023-10-30 19:29
Works on osx, error on win10

From: Georg ***@***.***>
Reply to: ScientiaFelis/sebmsR ***@***.***>
Date: Monday, 30 October 2023 at 17:56
To: ScientiaFelis/sebmsR ***@***.***>
Cc: Lars Pettersson ***@***.***>, Author ***@***.***>
Subject: Re: [ScientiaFelis/sebmsR] abundance_year_compare does not save (Issue #23)


Cannot reproduce error!?

**Comment by ScientiaFelis** [comment] 2023-10-31 07:38
Not sure how to fix the win10 error. Do you have any idea of what is causing it?

The font error perhaps could be fixed by having Arial installed, which it should be, then import it in R with:

```
extrafont::font_import()

```

And perhaps

```
extrafont::loadfonts(device = "pdf", quiet = TRUE)
extrafont::loadfonts(device = "postscript", quiet = TRUE)
extrafont::loadfonts(device = "win", quiet = TRUE)
 ```

**Comment by larspett** [comment] 2023-10-31 07:44
Will try again. Arial is there so that shouldn’t be the problem

31 okt. 2023 kl. 08:39 skrev Georg ***@***.***>:

﻿

Not sure how to fix the win10 error. Do you have any idea of what is causing it?

The font error perhaps could be fixed by having Arial installed, which it should be, then import it in R with:

extrafont::font_import()



And perhaps

extrafont::loadfonts(device = "pdf", quiet = TRUE)
extrafont::loadfonts(device = "postscript", quiet = TRUE)
extrafont::loadfonts(device = "win", quiet = TRUE)

**Comment by larspett** [comment] 2023-10-31 08:13
It didn't throw the font error messages now but I believe that was because I ran sebms_species_per_sitetype_plot(year=2022) first and got the errors (of the session) there. Or - maybe not. I restarted R now and ran sebms_abundance_year_compare_plot(year = 2021:2022) but didn't get any font errors. The fonts look ok too (which they don't in the sebms_species_per_sitetype_plot() .

However, on my windows machine, it writes an empty "Butterflynumber_2021" (0kB) with no suffix. I think my Mac did write a proper graph yesterday.

**Comment by larspett** [comment] 2023-10-31 08:27
Unlikely that the save fail is a mac thing. I tried testing on my laptop now but Box Sync with my R files isn't up to date so  that will take a while, But it is more likely that there is a bug in that function and that I was wrong when I thought I saw it being created on my mac at home

**Comment by ScientiaFelis** [comment] 2023-10-31 08:31
Ok, that is odd.
I will see if I can figure out what is wrong

**Comment by larspett** [comment] 2023-10-31 14:00
It saved nicely on a mac but fails on a PC, still making a 0 kB file with no suffix. The built png cuts the top Y axis value (18000) so needs to be fixed. 

There is something funny about the week numbers too. compare these two, one from the last report and one from the package
![sebmsr20-21](https://github.com/ScientiaFelis/sebmsR/assets/19598308/a011a116-cb16-4f4c-b60f-f3baeb6f1e0c)
![report-20-21](https://github.com/ScientiaFelis/sebmsR/assets/19598308/d313046c-be70-4260-aaee-64f60df08a1b)

**Comment by larspett** [comment] 2023-10-31 16:46
Ok, yes it looks so

**Comment by ScientiaFelis** [comment] 2023-11-01 11:11
Is this still failing @larspett ?

**Comment by larspett** [comment] 2023-11-01 12:47
No font error thrown bit does not save

**Comment by larspett** [comment] 2023-11-01 15:53
and the png is still 0 kB

**Comment by ScientiaFelis** [comment] 2023-11-01 18:26
I think it is fixed in the latest push.
I had forgot a bugtracer in the code. Strange that it worked at all

**Comment by larspett** [comment] 2023-11-02 13:23
Butterflynumber is still 0 kB in latest version (1.4.7)

**Comment by ScientiaFelis** [comment] 2023-11-02 13:31
I cannot see why.
It is still a Windows problem right?

**Comment by ScientiaFelis** [comment] 2023-11-02 15:56
Replace : to - in file names
Windows should be able to handle it now.

**Closed** 2023-11-02 17:18 UTC
Labels: bug, platform:Windows
